TeatroUD/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from rest_framework import routers
from teatros import views as theaters_views

# Api router
router = routers.DefaultRouter()
router.register('country', theaters_views.PaisViewSet, basename='Pais')
router.register('type/calendar', theaters_views.TipoCalendarioViewSet, basename='Tipo calendario')
router.register('type/artwork', theaters_views.TipoObraViewSet, basename='Tipo obra')
router.register('dramaturge', theaters_views.DramaturgoViewSet, basename='Dramaturgo')
router.register('theater', theaters_views.TeatroViewSet, basename='Teatro')

urlpatterns = [
    path('admin/', admin.site.urls),
    # core
    path('', include(('core.urls', 'core'), namespace="home")),
    # users
    path('users/', include(('users.urls', 'users'), namespace="users")),
    
    # Api routes
    path('api/', include(router.urls)),
    #path('api/country/', theaters_views.PaisViewSet.as_view({'get': 'list'}))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from core import views as home_views

urlpatterns = [
    path('', home_views.home_feed, name="feed"),
]

users/urls.py
from django.urls import path, include

from users import views as users_views

# rest_framework
from rest_framework import routers
router = routers.DefaultRouter()
# En el router vamos añadiendo los endpoints a los viewsets
#router.register('persona', users_views.PersonasViewSet)

urlpatterns = [
    path('',users_views.home, name="home"),
    path('login/',users_views.login_view, name="login" ),
    path('logout/',users_views.logout_view, name="logout" ),
    path('signup/',users_views.signup_view, name="signup" ),
    #API
    #path('api/', include(router.urls)),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body>
    {% include "nav.html" %}
    <br class="mt-5">
    <div class="container mt-5">
        {% block container %}
        {% endblock%}
    </div>

</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
	<div class="container">

		<a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="#">
			<img src="{% static 'img/logo.png' %}" height="45" class="d-inline-block align-top" /> Teatro UD
		</a>

		<div class="collapse navbar-collapse">

			<ul class="navbar-nav mr-auto">

				<li class="nav-item">
					<a href="{% url "admin:index" %}" >
						<img src="{% static 'img/default-profile.png' %}" height="35"
							class="d-inline-block align-top rounded-circle" />
					</a>
				</li>

				<li class="nav-item nav-icon">
					<a href="#">
						<i class="fas fa-plus"></i>
					</a>
				</li>

				<li class="nav-item nav-icon">
					<a href="#">
						<i class="fas fa-calendar-alt"></i>
					</a>
				</li>

				<li class="nav-item nav-icon">
					<a href="{% url "users:logout" %}">
						<i class="fas fa-sign-out-alt"></i>
					</a>
				</li>

			</ul>
		</div>
	</div>
</nav>