TeatroUD/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from rest_framework import routers
from teatros import views as theaters_views

# Api router
router = routers.DefaultRouter()
router.register('country', theaters_views.PaisViewSet, basename='Pais')
router.register('type/calendar', theaters_views.TipoCalendarioViewSet, basename='Tipo calendario')
router.register('type/artwork', theaters_views.TipoObraViewSet, basename='Tipo obra')
router.register('dramaturge', theaters_views.DramaturgoViewSet, basename='Dramaturgo')
router.register('theater', theaters_views.TeatroViewSet, basename='Teatro')

urlpatterns = [
    path('admin/', admin.site.urls),
    # core
    path('', include(('core.urls', 'core'), namespace="home")),
    # users
    path('users/', include(('users.urls', 'users'), namespace="users")),
    
    # Api routes
    path('api/', include(router.urls)),
    #path('api/country/', theaters_views.PaisViewSet.as_view({'get': 'list'}))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from core import views as home_views

urlpatterns = [
    path('', home_views.home_feed, name="feed"),
]

users/urls.py
from django.urls import path, include

from users import views as users_views

# rest_framework
from rest_framework import routers
router = routers.DefaultRouter()
# En el router vamos añadiendo los endpoints a los viewsets
#router.register('persona', users_views.PersonasViewSet)

urlpatterns = [
    path('',users_views.home, name="home"),
    path('login/',users_views.login_view, name="login" ),
    path('logout/',users_views.logout_view, name="logout" ),
    path('signup/',users_views.signup_view, name="signup" ),
    #API
    #path('api/', include(router.urls)),
]

users/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User
from teatros.models import Obra, Calendario

# Create your models here.
# Tipo Documento
class TipoDocumento(models.Model):
    id_tipo_documento = models.SmallIntegerField(primary_key=True, null=False, unique=True)
    abreviacion = models.CharField(max_length=5, null=False)
    desc_tipo = models.CharField(max_length=50, null=False)
    def __str__(self):
        """Return describe type person."""
        return self.desc_tipo

# Persona
class Persona(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    cod_persona = models.CharField(max_length=11, primary_key=True, null=False, unique=True)
    # To do - Foreing Key
    id_tipo_documento = models.ForeignKey(TipoDocumento, default='no registra', on_delete=models.CASCADE, null=False, blank=False)
    numero_documento = models.CharField(max_length=11, null=False, blank=False, default='00000000000')

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return username."""
        return self.user.username

# Estudiante
class Estudiante(models.Model):
    cod_estudiante = models.CharField(max_length=11, primary_key=True, null=False, unique=True)
    nombre = models.CharField(max_length=30, default='no registra', null=False)
    apellido = models.CharField(max_length=30, default='no registra', null=False)
    fecha_inscripcion = models.DateField(default=datetime.today, null=False)
    fecha_nacimiento = models.DateField(default=datetime.today,null=False)
    correo = models.EmailField(max_length=40, default='example@example.com', null=False)
    cod_unidad_estudiante = models.ForeignKey('users.unidad', on_delete=models.CASCADE, default='00001', null=False)
    def __str__(self):
        """Return describe type person."""
        return '{} {}'.format(self.apellido, self.nombre)

class AsistenciaEstudiante(models.Model):
    consec_asistencia = models.DecimalField(max_digits=4, decimal_places=0, primary_key=True)
    conse_calendario = models.ForeignKey(Calendario, on_delete=models.PROTECT, null=False, blank=False, default='1')
    id_obra = models.ForeignKey(Obra, on_delete=models.PROTECT, default='0001', null=False, blank=True)
    cod_estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE, default='20222020001', null=False, blank=True)
    def __str__(self):
        """Return describe type person."""
        return self.cod_estudiante

class Personaje(models.Model):
    id_personaje = models.CharField(max_length=4, primary_key=True, null=False, unique=True)
    id_obra = models.ForeignKey(Obra, on_delete=models.PROTECT, default='0001', null=False, blank=True)
    nom_personaje = models.CharField(max_length=40, null=False, blank=False, default=' ',)
    def __str__(self):
        """Return describe type person."""
        return self.nom_personaje

class PersonajeEstudiante(models.Model):
    consec = models.DecimalField(max_digits=4, decimal_places=0, primary_key=True)
    id_personaje = models.ForeignKey(Personaje, on_delete=models.PROTECT, default='0001', null=False, blank=True)
    id_obra = models.ForeignKey(Obra, on_delete=models.PROTECT, default='0001', null=False, blank=True)
    cod_estudiante = models.ForeignKey(Estudiante, on_delete=models.PROTECT, default='0001', null=False, blank=True)
    fecha_inicio = models.DateField(default=datetime.now)
    fecha_fin = models.DateField(default=datetime.now)
    def __str__(self):
        """Return describe type person."""
        return self.id_personaje

class Unidad(models.Model):
    cod_unidad = models.CharField(max_length=5, primary_key=True, null=False, unique=True)
    tipo_unidad = models.CharField(max_length=2, null=False, blank=True)
    uni_cod_unidad = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    nom_unidad = models.CharField(max_length=40, null=False, blank=True)
    def __str__(self):
        """Return describe type person."""
        return self.nom_unidad

class TipoUnidad(models.Model):
    tipo_unidad = models.CharField(max_length=2, primary_key=True, null=False, unique=True)
    desc_tipo_unidad = models.CharField(max_length=30, null=False, blank=True)
    def __str__(self):
        """Return describe type person."""
        return self.desc_tipo_unidad

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.template.loader import render_to_string, get_template
from django.conf import settings
from django.contrib import messages

# Exception
from django.db.utils import IntegrityError
import time

#Utils
from users.models import Persona
from datetime import datetime

#from .serializers import PersonaSerializer,ComisarioEventoSerializer,TareaSerializer,TipoPersonaSerializer
#from rest_framework import viewsets

# Create your views here.

def home(request):
    return redirect('users:login')

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect('home:feed')
            #return redirect('admin:index')
        else:
            return render(request, 'users/login.html', { 'error': 'Usuario o contraseña invalido.'})
    # Si el usuario ya está autenticado
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('home:feed')
    return render(request, 'users/login.html')

@login_required
def logout_view(request):
    logout(request)
    return redirect('users:login')

def signup_view(request):
    if request.method == 'POST':

        username = request.POST['username']
        passwd = request.POST['passwd']
        passwd_confirmation = request.POST['passwd_confirmation']

        if passwd != passwd_confirmation:
            return render(request, 'users/signup_view.html', {'error': 'La confirmación de la contraseña no coincide'})

        #user = User.objects.create_user(username=username, password=passwd)
        try:
            user = User.objects.create_user(username=username, password=passwd)
        except IntegrityError:
            return render(request, 'users/signup_view.html', {'error': 'El nombre de usuario ya está en uso'})

        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']
        user.email = request.POST['email']
        #user.id = request.POST['cod_persona']
        user.save()


        #Enviando correo
        template = render_to_string('email/confirmation.html',{
          'name': (user.first_name+' '+user.last_name),
          'email': user.email,
          }
        )
        #templateGet = get_template('email/confirmation.html')
        #content = templateGet.render({'mail': user.email,})

        subject = 'Su cuenta ha sido creada'
        email = EmailMessage(
          subject,
          template,
          settings.EMAIL_HOST_USER,
          ['correopruebasud@gmail.com'],
        )
        email.content_subtype = "html" 
        email.fail_silently=False
        #email.content_subtype = "html" 
        #email.attach_alternative(template,'text/html')
        email.send()
        messages.success(request, 'Por favor revisa tu correo')
        print('SE ENVÍA CORREO DE PRUEBA')


        persona = Persona(user=user)
        persona.cod_persona = request.POST['cod_persona']
        #persona.id_tipo_persona_fk = request.POST['tipo_persona']
        persona.save()
        return redirect('users:login')

    return render(request, 'users/signup_view.html')


templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">

                <img src="{% static "img/logo.png" %}" class="img-fluid rounded mx-auto d-block pb-4"
                        style="max-width: 60%;">

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>

</body>
</html>

templates/users/login.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Teatro UD - Sign in</title>
{% endblock%}

{% block container %}

{% if error %}
	<p class="alert alert-danger">{{ error }}</p>
{% endif%}

<form method="POST" action="#">
	{% csrf_token %}
	<div class="form-group">
		<input class="form-control" type="text" placeholder="Username" name="username" />
	</div>
	<div class="form-group">
		<input class="form-control" type="password" placeholder="Password" name="password" />
	</div>
	<div class="form-group">
		<button class="btn btn-primary btn-block mt-5" type="submit">Sign in!</button>
	</div>
</form>
<p class="mt-4">Don't have an account yet? <a href="{% url "users:signup" %}">Sign up here.</a></p>

{% endblock %}

templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Sign up</title>
{% endblock %}

{% block container %}

    <form action="{% url 'user:signup' %}" method="POST">
        {% csrf_token %}

        <button class="btn btn-primary btn-block mt-5" type="submit">Register!</button>

    </form>

{% endblock %}

templates/users/signup_view.html
{% extends "users/base.html" %}

{% block container %}

    {% if error %}
        <p class="alert alert-danger">{{ error }}</p>
    {% endif %}

    <form action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %}

        {% if messages%}
         {% for message in messages%}
            <div class="alert alert-success" role="alert">
                {{message}}
            </div>
         {% endfor%}
        {% endif %}
        
        <div class="form-group">
            <input class="form-control" type="text" placeholder="Username" name="username" required="true" />
        </div>

        <div class="form-group">
            <input class="form-control" type="password" placeholder="Password" name="passwd" required="true" />
        </div>

        <div class="form-group">
            <input class="form-control" type="password" placeholder="Password confirmation" name="passwd_confirmation" required="true" />
        </div>

        <div class="form-group">
            <input class="form-control" type="text" placeholder="Código persona" name="cod_persona" required="true" />
        </div>

        <!-- <div class="form-group">
            <input class="form-control" type="text" placeholder="Tipo persona" name="tipo_persona" required="true" />
        </div>-->

        <div class="form-group">
            <input class="form-control" type="text" placeholder="First name" name="first_name" required="true" />
        </div>

        <div class="form-group">
            <input class="form-control" type="text" placeholder="Last name" name="last_name" required="true" />
        </div>

        <div class="form-group">
            <input class="form-control" type="email" placeholder="Email address" name="email" required="true" />
        </div>

        <button class="btn btn-primary btn-block mt-5" type="submit">Register!</button>

    </form>

{% endblock %}